language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - yarn lint
  - yarn build --base-href /WersaPlayer/
  - mv dist/WersaPlayer/index.html dist/WersaPlayer/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/WersaPlayer
  on:
    branch: master